name: Ping URL

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Ping URL
        run: curl -X GET -H "Authorization: token ${{ secrets.PAT }}" https://beatconnection.onrender.com
