name: Ping URL every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  ping-url:
    runs-on: ubuntu-latest

    steps:
      - name: Curl URL
        run: curl -sSf https://beatconnection.onrender.com
